default: &default
  adapter: postgresql
  encoding: unicode
  username: 'book'
  password: 'imabook'
  host: localhost

development:
  <<: *default
  database: askmybook_development

test:
  <<: *default
  database: askmybook_test