default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.ASKMYBOOK_DATABASE_USER %>
  password: <%= Rails.application.credentials.ASKMYBOOK_DATABASE_PASSWORD %>
  host: localhost
  port: 5436

development:
  <<: *default
  database: askmybook_development
  username: <%= Rails.application.credentials.ASKMYBOOK_DATABASE_USER %>
  password: <%= Rails.application.credentials.ASKMYBOOK_DATABASE_PASSWORD %>

test:
  <<: *default
  database: askmybook_test

production:
  <<: *default
  database: askmybook_production
  port: 5432
  username: <%= Rails.application.credentials.ASKMYBOOK_PROD_DATABASE_USER %>
  password: <%= Rails.application.credentials.ASKMYBOOK_PROD_DATABASE_PASSWORD %>