default: &default
  adapter: postgresql
  encoding: unicode
  username: 'book'
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: askmybook_development

test:
  <<: *default
  database: askmybook_test