default: &default
  adapter: postgresql
  encoding: unicode
  username: 'book'
  password: <%= ENV['ASKMYBOOK_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5436

development:
  <<: *default
  database: askmybook_development

test:
  <<: *default
  database: askmybook_test

production:
  <<: *default
  database: askmybook_production
  username: askmybook
  password: <%= ENV["ASKMYBOOK_DATABASE_PASSWORD"] %>